- name: install etcd service.
  yum: pkg=etcd state=present

- name: Create etcd service related directory.
  file:
    path: '{{ ETCD_CERT_PATH  }}'
    owner: etcd
    group: etcd
    mode:  0755
    state: directory

- name: Create etcd data directory.
  file:
    path: '{{ ETCD_DATA_PATH  }}'
    owner: etcd
    group: etcd
    mode:  0700
    state: directory

- name: Create etcd certificate on the first etcd server
  shell: '/bin/cp -rf {{ KUBE_CERTS_PATH }}/{ca.pem,ca-key.pem,etcd.pem,etcd-key.pem} {{ ETCD_CERT_PATH  }}'
  run_once: true
  delegate_to: "{{ groups['etcd-nodes'][0] }}"

- name: Slurp etcd certificate on the first etcd server.
  slurp:
    src: "{{ item }}"
  register: ETCD_CERTS
  run_once: true
  delegate_to: "{{ groups['etcd-nodes'][0] }}"
  with_items:
    - "{{ ETCD_CERT_PATH }}/ca.pem"
    - "{{ ETCD_CERT_PATH }}/ca-key.pem"
    - "{{ ETCD_CERT_PATH }}/etcd.pem"
    - "{{ ETCD_CERT_PATH }}/etcd-key.pem"

- name: Copy etcd certificate file to other etcd servers.
  copy:
    dest: "{{ item.item }}"
    content: "{{ item.content | b64decode }}"
    owner: etcd
    group: etcd
    mode: 0600
  with_items: "{{ ETCD_CERTS.results }}"

- name:  Copy etcd file into install directory.
  template:
    src:  etcd.conf
    dest: '{{ ETCD_HOME_PATH }}/etcd.conf'
    owner: etcd
    group: etcd
    mode:  0644

- name: Restart etcd service.
  systemd:
    state: restarted
    daemon_reload: yes
    name: etcd
    enabled: yes
