- name: Create Kubernets kubelet logs directory.
  file:
    path: '{{ KUBE_LOGS_PATH  }}/kubelet'
    owner: root
    group: root
    mode:  0755
    state: directory

- name: Create Kubernets kubelet data directory.
  file:
    path: '{{ KUBE_KUBELET_DIR }}'
    owner: root
    group: root
    mode:  0755
    state: directory

- name:  Copy kube-config file into install directory.
  template:
    src:  kube-config
    dest: '{{ KUBE_HOME_PATH }}/etc/kube-config'
    owner: root
    group: root
    mode:  0644

- name:  Copy kubelet file into install directory.
  template:
    src:  kubelet
    dest: '{{ KUBE_HOME_PATH }}/etc/kubelet'
    owner: root
    group: root
    mode:  0644

- name:  Copy kubelet config file into install directory.
  template:
    src:  kubelet.config
    dest: '{{ KUBE_HOME_PATH }}/etc/kubelet.config'
    owner: root
    group: root
    mode:  0644

- name:  Copy kubelet kubeconfig file into install directory.
  template:
    src:  kubelet.kubeconfig
    dest: '{{ KUBE_HOME_PATH }}/etc/kubelet.kubeconfig'
    owner: root
    group: root
    mode:  0644

- name:  Copy kubelet service file into install directory.
  template:
    src:  kubelet.service
    dest: /usr/lib/systemd/system/kubelet.service 
    owner: root
    group: root
    mode:  0644

- name: Restart kubelet service.
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
    enabled: yes
