- name: Unarchive Kubernets bin files into install directory.
  unarchive:
    src:  'kubernetes-{{ KUBE_VERSION }}.tar.gz'
    dest: '{{ KUBE_HOME_PARENT }}'

- name: Create a Kubernets directory link.
  file:
    src:  '{{ KUBE_HOME_PARENT }}/kubernetes-{{ KUBE_VERSION }}'
    dest: '{{ KUBE_HOME_PATH }}'
    owner: root
    group: root
    state: link

- name: Create kubernetes master certificate on the first kubernetes server.
  shell: '/bin/cp -f {{ KUBE_CERTS_PATH }}/{ca.pem,kubelet.pem,kubelet-key.pem,kube-proxy.pem,kube-proxy-key.pem} {{ KUBE_HOME_PATH }}/etc/ssl'
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: Slurp kubernetes master certificate on the first kubernetes server.
  slurp:
    src: "{{ item }}"
  register: KUBE_NODE_CERTS
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"
  with_items:
    - "{{ KUBE_HOME_PATH }}/etc/ssl/ca.pem"
    - "{{ KUBE_HOME_PATH }}/etc/ssl/ca-key.pem"
    - "{{ KUBE_HOME_PATH }}/etc/ssl/kubelet.pem"
    - "{{ KUBE_HOME_PATH }}/etc/ssl/kubelet-key.pem"
    - "{{ KUBE_HOME_PATH }}/etc/ssl/kube-proxy.pem"
    - "{{ KUBE_HOME_PATH }}/etc/ssl/kube-proxy-key.pem"

- name: Copy kubernetes master certificate file to other kubernetes servers.
  copy:
    dest: "{{ item.item }}"
    content: "{{ item.content | b64decode }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ KUBE_NODE_CERTS.results }}"

# Install kubelet service
- include_tasks: kubelet_install.yml

# Install kube-proxy service
- include_tasks: kube-proxy_install.yml
