- name: Create Kubernets kube-controller-manager logs directory.
  file:
    path: '{{ KUBE_LOGS_PATH  }}/kube-controller-manager'
    owner: root
    group: root
    mode:  0755
    state: directory

- name:  Copy kube-controller-manager kubeconfig file into install directory.
  template:
    src:  'kube-controller-manager.kubeconfig'
    dest: '{{ KUBE_HOME_PATH }}/etc/kube-controller-manager.kubeconfig'
    owner: root
    group: root
    mode:  0644

- name:  Copy kube-controller-manager file into install directory.
  template:
    src:  kube-controller-manager
    dest: '{{ KUBE_HOME_PATH }}/etc/kube-controller-manager'
    owner: root
    group: root
    mode:  0644

- name:  Copy kube-controller-manager service file into install directory.
  template:
    src:  kube-controller-manager.service
    dest: /usr/lib/systemd/system/kube-controller-manager.service 
    owner: root
    group: root
    mode:  0644

- name: Restart kube-controller-manager service.
  systemd:
    state: restarted
    daemon_reload: yes
    name: kube-controller-manager
    enabled: yes
